include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-sing-box
PKG_VERSION:=0.1
PKG_RELEASE:=1

LUCI_TITLE:=LuCI Support for sing-box
LUCI_DEPENDS:=+sing-box
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk
# call BuildPackage - OpenWrt buildroot signature
